### ISSUE TITLE
[BUG] Certain apps in "Favorites" causes app crash

### ISSUE THREAD

**Issue by yuxiangwende** [Droid-ify/client#415] opened 2023-08-11 00:34 UTC
**Describe the bug**
I have added some apps into the "Favorites" library. then, every time when I scroll the list in the "Favorites", the app crashes. I try to unstar every app in "Favorites" one by one. but when the action moves to certain app, the app crashes. Now everytime I click the "Favorites" button, the app immediately crashes.

**To Reproduce**
1. add some apps to the "Favorites" library
2. Click on "..." button
3. clicke on "Favorites" button
4. Scroll the list in "Favorites"
5. app crashes.

**Expected behavior**
Display the list of "Favorites" apps and scroll the list smoothly.

**Smartphone (please complete the following information):**
 - Device: XiaoMi 10 Lite monet
 - OS: Android 12 (LineageOS)
 - Version [e.g. v0.5.7]

**Comment by Iamlooker** [comment] 2023-08-16 22:25
Duplicate of #336

**Closed** 2023-08-16 22:25 UTC
Labels: bug
