### ISSUE TITLE
Need 'no sleeping mode' in settings app 🚫🛏️

### ISSUE THREAD

**Issue by userkilled** [Droid-ify/client#588] opened 2023-11-27 21:30 UTC
Hello, after a lot of use I notice that the smartphone is starting to freeze. It's not about the program, but about normal performance.

How about adding a 'no sleep' option on repositories update time, so that the device waits for completion with the screen on. That would be better, you could, try, see progress

**Comment by Iamlooker** [comment] 2023-12-10 07:56
Lag caused by the repo syncing has been fixed and will be available in next release.

So, I think this is irrelevant now?

**Comment by userkilled** [comment] 2023-12-10 08:02
Let's see how I can get a new release. I might as well test on a slightly older device with 5.1.1. If that helps the improvement. Since the main client was also experiencing lags when updating repositories.

**Comment by Iamlooker** [comment] 2023-12-10 08:19
Yes the lag should be fixed in the coming release, yyou can test it in the alpha build

You can download the latest alpha builds from our [Telegram Community](https://t.me/droidifyc) or [Actions Tab](https://github.com/Droid-ify/client/actions/workflows/build_debug.yml)

**Comment by userkilled** [comment] 2023-12-10 08:27
https://github.com/Droid-ify/client/commit/daab36a0e52b64c0217f90b88d1e224b68a7a3bb

I'm waiting

**Comment by userkilled** [comment] 2023-12-10 08:38
It works well on the new device. I will write about the old one later

**Comment by Iamlooker** [comment] 2024-01-04 08:46
> It works well on the new device. I will write about the old one later
> 

Any updates?

**Comment by userkilled** [comment] 2024-01-04 11:05
I don't really understand how to put 21 api for android 5.1.1? After the build, there was an error when installing

**Comment by Iamlooker** [comment] 2024-01-05 16:13
Min SDK is 23 now. Because of new policy for Android: Check [here](https://bayton.org/android/android-14-minimum-sdk/)

**Closed by Iamlooker** 2024-01-05 16:13 UTC
Labels: enhancement

**Comment by TheLastProject** [comment] 2024-01-27 23:46
Google requires at least `targetSdk` 23. `minSdk` is still allowed to be lower, they don't block based on `minSdk`. So you don't have to drop support for older devices.
