### ISSUE TITLE
[Crash] Crashes if Shizuku is not running

### ISSUE THREAD

**Issue by RuiNtD** [Droid-ify/client#485] opened 2023-09-20 15:53 UTC
**Describe the bug**
If Shizuku isn't running and Droid-ify is set to use Shizuku, Droid-ify crashes on startup. 

**To Reproduce**
1. Start Shizuku and set Droid-ify to install with Shizuku
2. Close Droid-ify
3. Stop Shizuku
4. Attempt to open Droid-ify

**Smartphone:**
 - Device: Pixel 7a
 - OS: Android 13
 - Version: Droid-ify 0.5.8.4

**Additional context**

**Comment by Iamlooker** [comment] 2023-09-20 18:36
Duplicate of #480

**Closed by Iamlooker** 2023-09-20 18:36 UTC
Labels: bug
