### ISSUE TITLE
[BUG] Bad display format since latest patch 0.5.9

### ISSUE THREAD

**Issue by HarriBuh** [Droid-ify/client#539] opened 2023-10-24 14:24 UTC
**Describe the bug**
The latest patch introduced a new display format issue on my phone. I can hardly see and cannot select the top buttons.

**To Reproduce**
1. Open App after applying the update

**Screenshots**
![markup_1000001666](https://github.com/Droid-ify/client/assets/123186113/b81ed1ba-7147-4a99-8084-e898c5fa79c4)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 7
 - OS: Android 14
 - Version 0.5.9 Patch 4

**Comment by Iamlooker** [comment] 2023-10-24 14:53
Duplicate of #534

**Closed by Iamlooker** 2023-10-24 14:53 UTC
