### ISSUE TITLE
Might you raise the repo list a little in order to properly view the tick sign, please?

### ISSUE THREAD

**Issue by serrq** [Droid-ify/client#381] opened 2023-07-27 03:58 UTC
Android 13
OnePlus CPH2399
Droid-ify 0.5.7

![1000036435](https://github.com/Droid-ify/client/assets/113377431/ce78a9f5-e853-46cd-bb5c-2f842676db89)

**Comment by GameOverFlowChart** [comment] 2023-07-29 18:06
I had the same issue, seems to be independent of device.

**Comment by Iamlooker** [comment] 2023-08-02 05:55
yes, this is known and will be fixed in next release

**Comment by Iamlooker** [comment] 2023-08-02 05:56
Duplicate of #361

**Closed by Iamlooker** 2023-08-02 05:56 UTC
