### ISSUE TITLE
Basic Navigation for Android TV

### ISSUE THREAD

**Issue by KingLucius** [Droid-ify/client#353] opened 2023-06-15 11:26 UTC
**Is your feature request related to a problem? Please describe.**
For Android TV boxes without play store like Fire TV, or using my own F-Droid repo of APKs for Android TV.

**Describe the solution you'd like**
Basic Pad-D navigation without so much changing of the UI/UX

**Describe alternatives you've considered**
There is no alternatives

**Additional context**
Thank you for the great app

**Comment by KingLucius** [comment] 2023-06-16 08:01
After looking into source and tried to make a pull request to fix that behavior but i am not a kotlin guy
I have noticed that not all layout elements are isfocusable & isfocusableintouchmode which makes the navigation limited on Android TV to only the toolbar and can't navigate beyong that.

**Comment by Iamlooker** [comment] 2023-06-16 13:27
Sure I will work on this once I am done working on #309 

Also, Duplicate of #60

**Closed by Iamlooker** 2023-06-16 13:27 UTC
Labels: enhancement
