### ISSUE TITLE
export config/repo list

### ISSUE THREAD

**Issue by lu-ckystars** [Droid-ify/client#489] opened 2023-09-24 22:03 UTC
it's tedious setting droid-ify up across various devices/installs. it would be nice to be able to just backup and restore the settings.

**Comment by vdbhb59** [comment] 2023-10-22 11:26
This will be most useful.
If it gets implemented, cross app compatibility will be requested.

**Comment by Iamlooker** [comment] 2023-10-23 09:16
Duplicate of #145

**Closed** 2023-10-23 09:16 UTC
