### ISSUE TITLE
Add apks directly from github

### ISSUE THREAD

**Issue by Black-StellarSpectrum** [Droid-ify/client#509] opened 2023-10-09 10:51 UTC
**Is your feature request related to a problem? Please describe.**
Recently I had an app who had different signature on GitHub as apk and different on f droid, fdroid's updates were delayed by multiple versions and I was unable to update the app.

**Describe the solution you'd like**
So if possible this could be the solution, So add GitHub as a source for apk as well, like if the GitHub page has apk under release then add that so I can update GitHub version via the droidify app, it'd be a life saver, also there are some apps which aren't on fdroid but available on GitHub as apks, so I'd be able to update them as well. 

**Describe alternatives you've considered**
Only alt was I had to uninstall the app and reinstall it from github, and check for updates everytime on GitHub. 

**Additional context**
I don't know if it's possible or anyone has thought about it, but having GitHub as a source of apk and "What's new" would be really helpful and expand the app library even more!

**Comment by Iamlooker** [comment] 2023-10-10 11:21
Duplicate of #18

**Closed by Iamlooker** 2023-10-10 11:21 UTC

**Comment by realeatham** [comment] 2024-02-02 09:22
Use the obtainium app. It's available from izzyondroid

**Comment by Black-StellarSpectrum** [comment] 2024-02-02 09:25
> Use the obtainium app. It's available from izzyondroid 

Yes, using that and it's a good app, really helpful!
