### ISSUE TITLE
Question/Request: Does Droid-ify install updates to apps if eg. signature has changed?

### ISSUE THREAD

**Issue by DB9-max** [Droid-ify/client#852] opened 2024-11-12 21:08 UTC
Sometimes I edit apps a little bit and then need to sign them myself. F-droid app doesn't update an app if it's signature has changed - but does Droid-ify? 

Neo Store does but that is sometimes very unstable and laggy - nice app though.

Id like to see much more of Droid-ify it's a very promising app.

**Comment by Iamlooker** [comment] 2024-11-17 14:06
Not yet, it is available is an old aplha build in the telegram group. Idk when I will be updating here


You can download the latest alpha builds from our [Telegram Community](https://t.me/droidifyc) or [Actions Tab](https://github.com/Droid-ify/client/actions/workflows/build_debug.yml)

**Comment by Iamlooker** [comment] 2024-11-17 14:06
Duplicate of #578

**Closed** 2024-11-17 14:07 UTC
Labels: enhancement
