### ISSUE TITLE
[Feature request] Tab Download

### ISSUE THREAD

**Issue by Pantyhose-X** [Droid-ify/client#453] opened 2023-08-30 04:18 UTC
**Is your feature request related to a problem? Please describe.**
I downloaded multiple apps at the same time and had to search and click install again and again
Please try to add this feature.it is an important feature because when you download many app inside background. you have to search that apps for install. If all download apps are shown in one tab that is easier for install.
**Describe the solution you'd like**
add Tab that Download In progress

**Comment by Iamlooker** [comment] 2023-09-14 20:24
Duplicate of #43

**Closed by Iamlooker** 2023-09-14 20:24 UTC
Labels: enhancement
