### ISSUE TITLE
Backup/Restore (repos, app installed, settings, etc.)

### ISSUE THREAD

**Issue by serrq** [Droid-ify/client#145] opened 2022-10-19 08:10 UTC
The repositories are starting to be many, the installed apps don't need to be saved in their entirety, just the list of headers so that if I need to move to a new device I upload the droid-ify.zip file and just have to download all the apps that are already there but just need to be pulled down from the network.
Same thing for the settings.

A selective backup would be needed for the list of apps so that customized backups could be created to share to other people.

**Comment by vertigo220** [comment] 2022-12-11 20:43
Semi-duplicate of issue #19, only difference being this involves backing up list of installed apps as well.

**Comment by its-thomas** [comment] 2023-04-19 10:16
May I ask when we might be able to have the above features in an update of your awesome Droid-ify app? 😍

**Comment by laraib07** [comment] 2023-04-26 13:09
Also backup list of favourite apps

**Comment by Iamlooker** [comment] 2023-05-02 18:31
> May I ask when we might be able to have the above features in an update of your awesome Droid-ify app? 😍

I cannot guarantee the time but this will come after the new index format is implemented

**Comment by zerobun** [comment] 2023-09-23 15:55
Just came here to create a issue about this, hope it gets implemented soon🙏❤️

**Comment by Iamlooker** [comment] 2023-10-24 20:04
Only installed app feature is not implemented yet. And is not planned in near future. As many micro issues with installer needs to be fixed and a larger `InstallManager` implementation is needed

**Closed** 2023-10-28 17:01 UTC
Labels: enhancement
