### ISSUE TITLE
Is Droid-ify app fully compatible with Android TV 12?

### ISSUE THREAD

**Issue by serrq** [Droid-ify/client#532] opened 2023-10-22 08:43 UTC
I would to buy a tv box soon. Thanks in advance.

**Comment by Iamlooker** [comment] 2023-10-23 03:18
No we need more testers for it. I will be working on simple navigation fixes for now.

A revamped UI for TV will be available later.

Duplicate of #60

**Closed by Iamlooker** 2023-10-23 03:18 UTC
