### ISSUE TITLE
[BUG] Theme + UI overlap issues

### ISSUE THREAD

**Issue by o0nd7ots** [Droid-ify/client#542] opened 2023-10-25 09:31 UTC
**Bug description**
When I launch droidify, sometimes it ignores the material you option, and then the UI is not adjusted for the camera bump/status bar.
(re)flipping the material you switch fixes the issue, but it comes back after reboot.

When the bug is there, its hard to use the UI.

**To Reproduce**
1. Set Material You colors in Android
2. Restart the phone
3. Launch Droidify (unidentified theme - screen 1)
4. (re)flip the material you switch (fixes the issue - screen 2)
5. Kill droidify
6. Start droidify and turn off material you (true default color? - screen 3)

**Expected behavior**
- theme is not purple (not the default color nor the material you color)
- status bar does not overlap with app UI

**Screenshots**
Screen1:
![image](https://github.com/Droid-ify/client/assets/124466962/0c5f94d8-b670-4b93-b381-990db32b99dd)
Screen2:
![image](https://github.com/Droid-ify/client/assets/124466962/a916d982-94fe-42d7-95ce-118690ee6bb0)
Screen3:
![image](https://github.com/Droid-ify/client/assets/124466962/8191fb32-b74e-4961-a276-4625922698a5)

**Smartphone**
 - Device: Realme 7 pro
 - OS: Realme UI 3.0 (Android 12)
 - Version v0.59-4

**Additional context**
AFAIR does not happen for v59-3

**Comment by Iamlooker** [comment] 2023-10-25 10:51
Duplicate of #535

**Closed by Iamlooker** 2023-10-25 10:51 UTC
Labels: bug
